import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
    return (
        <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
            <p style={{ fontSize: "18px", marginBottom: "30px" }}>
                This project was generated By{" "}
                <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
                    Dhiwise
                </a>
                • Quickly use below links to navigate through all pages.
            </p>
            <ul style={{ listStyle: "none", padding: "0" }}>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/friendlist" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        FriendList
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/activityfeed" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        ActivityFeed
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/addfriends" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        AddFriends
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/instagramsignin" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        InstagramSignin
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/facebookfeed" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        FacebookFeed
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/followers" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        Followers
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/useraccount" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        UserAccount
                    </Link>
                </li>
                <li style={{ marginBottom: "10px" }}>
                    <Link to="/feedPage" style={{ color: "#87CEFA", textDecoration: "none" }}>
                        TwitterFeed
                    </Link>
                </li>
            </ul>
        </div>
    );
};

export default Home;